In [1]:
import torch

Create a tensor a from list(range(9)). Predict and then check the size, offset, and stride. 
- Create a new tensor using `b = a.view(3, 3)`. What does view do? Check that a and b share the same storage. 
- Create a tensor `c = b[1:,1:]`. Predict and then check the size, offset, and stride.

In [13]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

size: [9], offset: 0, stride: (1,)

In [14]:
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

In [15]:
b = a.view(3,3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

view gives us a view on the same underlying storage.

In [16]:
id(b.storage()) == id(a.storage())

True

In [11]:
c = b[1:,1:]

size: [2,2], offset:1, stride:(2, 1)

In [12]:
t.size(), t.storage_offset(), t.stride()

(torch.Size([9]), 0, (1,))

doh! pretty wrong there.

2. Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?
  - Apply the function element-wise to a. Why does it return an error?
  - What operation is required to make the function work?
  - Is there a version of your function that operates in place?

In [17]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [22]:
# this is the in-place operation, which fails because the tensor is of the wrong type for the output of cos
torch.cos_(a)

RuntimeError: result type Float can't be cast to the desired output type Long

In [21]:
# so we convert it to float32. I was surprised that float16 didn't work!
torch.cos(a.to(dtype=torch.float32))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])